### PR TITLE
Harsh/bug fix

### LINKED ISSUE #80: Bug -[Doctor] Update Doctor Profile Screen
**Describe the bug**

- Click on add slot show startTime and EndTime
- if user selected StartTime value then endTime always after start time.
- once one slot added then onwards slot added that time slot after value.
- Add delete icon right side added time slot
- Time 24 hrs

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### PR DESCRIPTION
**Pull request by HarshPanchalInfusion**
PR for add time shiftwise.

### CODE REVIEW

**Review by vikas-infusion — DISMISSED** [review]

File: app/src/main/java/com/android/doctorapp/util/bindingAdapter/BindingAdapters.kt [hunk 1]
```diff
@@ -208,7 +208,19 @@ fun convertDateFormat(textView: TextView, originalDateStr: String) {
 
 @BindingAdapter("app:appointmentTime")
 fun convertTimeFormat(textView: TextView, originalTimeStr: String) {
-    textView.text = convertTime(originalTimeStr)
+    when (originalTimeStr) {
+        "Start Time" -> {
+            textView.text = "Start Time"
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/util/bindingAdapter/BindingAdapters.kt:213]: added this text in string.xml file

**Review by vikas-infusion — APPROVED** [review]
