### PR TITLE
Harsh/calendar bug fix

### LINKED ISSUE #135: Bug - [Doctor] Calendar date issue
**Describe the bug**
- One user select any date in calendar then again click on calendar icon then calendar open that time show last selected date instead of current date.
- If change tab and then click on calendar icon open calendar then show current date.

**To Reproduce**
1. Go to Request tab
2. Click on calendar icon.
3. Select any date 
4. Again click on calendar icon then show calendar current date selected instead of last selected date.

**Expected behavior**
- Show last selected date in calendar

**Screenshots**

Screenshot 2023-09-28 at 11 17 34 AM

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### PR DESCRIPTION
**Pull request by HarshPanchalInfusion**
PR for Calendar Bug Brnach

### CODE REVIEW

File: app/src/main/java/com/android/doctorapp/ui/doctor/UpdateDoctorProfileFragment.kt [hunk 1]
```diff
@@ -96,6 +96,10 @@ class UpdateDoctorProfileFragment :
     private var tempShiftTimeList = ArrayList<AddShiftTimeModel>()
 
     lateinit var bottomSheetFragment: BottomSheetDialog
+
+    lateinit var updateProfileCalender: Calendar
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/doctor/UpdateDoctorProfileFragment.kt]: Define calendar object in baseFragment show any fragment can easily access and no need to create each every fragment inside it instance.

Like     var myCalender: Calendar = Calendar.getInstance()

Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/doctor/UpdateDoctorProfileFragment.kt]: Done

**Review by vikas-infusion — APPROVED** [review]
