### PR TITLE
Namrata/login signup

### LINKED ISSUE #6: User login screen
Create screen for User login using [screen](https://drive.google.com/file/d/1CrsR4P_3LviwrtNSoOD5XPg0GT4gvAjs/view?usp=drive_link).

- [x] Screen will have Logo, Login title, email input field, password input field, forgot password title(ignore functionality for now), Log in button, Don't have account Sign up label.
- [x] Fields are mandatory so display error messages when user type email and password. Email error - "Please enter valid email", Password - Password should contain atleast one small, one capital, one special symbol and should contain at least 8 characters.
- [ ] Sign in button will be enabled after user enter valid email and password.
- [x] Sign up label would be clickable and should take user to Signup screen Home screen.
- [x] In case of failure, display dialog with information - for wrong credentials "You have entered wrong email or password"

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### PR DESCRIPTION
**Pull request by namratacn**
Implemented login screen.
Added the validation for email and password. 
when user click on login button it check the email and password firebase authentication. if email and password is correct then navigate to addUserProfile screen. else its show the dialog box foe incorrect email or password.
Also put the one SignUp lable for navigate to Registration screen.

### CODE REVIEW

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt [hunk 1]
```diff
@@ -38,6 +50,15 @@ class LoginFragment : BaseFragment<FragmentLoginBinding>(R.layout.fragment_login
         savedInstanceState: Bundle?
     ): View {
         super.onCreateView(inflater, container, savedInstanceState)
+
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt:45]: please add this code into viewmodel and call into init method.

```
val googleSignInOptions = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.client_id))
            .requestEmail()
            .build()

        // Initialize sign in client
        googleSignInClient = GoogleSignIn.getClient(requireActivity(), googleSignInOptions)
```

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt [hunk 2]
```diff
@@ -60,14 +81,57 @@ class LoginFragment : BaseFragment<FragmentLoginBinding>(R.layout.fragment_login
...
+        }
+
     }
+
+    private val launcher =
+        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
+            //Check condition
+            if (result.resultCode == AppCompatActivity.RESULT_OK) {
+                // When request code is equal to RESULT_OK initialize task
+                val signInAccountTask: Task<GoogleSignInAccount> =
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt]: This code move to repository class. get back to response in view model

```
    val signInAccountTask: Task<GoogleSignInAccount> =
                    GoogleSignIn.getSignedInAccountFromIntent(result.data)
```

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt [hunk 3]
```diff
@@ -60,14 +81,57 @@ class LoginFragment : BaseFragment<FragmentLoginBinding>(R.layout.fragment_login
...
+                    GoogleSignIn.getSignedInAccountFromIntent(result.data)
+
+                if (signInAccountTask.isSuccessful) {
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginFragment.kt]: if any async operation please put in repository class

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt [hunk 4]
```diff
@@ -10,57 +12,105 @@ import com.android.doctorapp.repository.AuthRepository
...
+
+    val signInAccountTask: MutableLiveData<Task<GoogleSignInAccount>> = MutableLiveData()
+    val googleSignInAccount: MutableLiveData<GoogleSignInAccount> = MutableLiveData()
+    val authCredential: MutableLiveData<AuthCredential> = MutableLiveData()
+
+
+
+
+
     init {
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt:57]: auth object available in BaseViewModel class.

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt [hunk 5]
```diff
@@ -10,57 +12,105 @@ import com.android.doctorapp.repository.AuthRepository
...
         auth = FirebaseAuth.getInstance()
+
+        val googleSignInOptions = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt]: put this googleSignInOptions object in baseViewModel class.

File: app/src/main/java/com/android/doctorapp/ui/profile/AddUserProfileFragment.kt [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+import com.android.doctorapp.R
+import com.android.doctorapp.databinding.FragmentAddUserProfileBinding
+import com.android.doctorapp.di.AppComponentProvider
+import com.android.doctorapp.di.base.BaseFragment
+import com.android.doctorapp.di.base.toolbar.FragmentToolbar
+
+
+class AddUserProfileFragment : BaseFragment<FragmentAddUserProfileBinding>(R.layout.fragment_add_user_profile) {
+
+    override fun builder() =FragmentToolbar.Builder()
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/profile/AddUserProfileFragment.kt]: File not formatted.

File: app/src/main/res/drawable/button_state_colors.xml [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+<selector xmlns:android="http://schemas.android.com/apk/res/android">
+    <item android:state_enabled="true">
+        <shape android:shape="rectangle">
+            <solid android:color="@color/blue"/>
+            <corners android:radius="@dimen/margin_10"/>
+        </shape>
+    </item>
+    <item android:state_enabled="false">
+        <shape android:shape="rectangle">
+            <solid android:color="@color/grey"/>
```
Comment (vikas-infusion) [inline app/src/main/res/drawable/button_state_colors.xml]: For gray color use this color code #e5e5e5

File: app/src/main/res/drawable/round_button.xml [hunk 8]
```diff
@@ -0,0 +1,7 @@
+<?xml version="1.0" encoding="utf-8"?>
+<shape xmlns:android="http://schemas.android.com/apk/res/android"
+    android:shape="rectangle" android:padding="10dp">
+    <solid android:color="#1a4d91"/>
+    <corners android:radius="10dp"/>
```
Comment (vikas-infusion) [inline app/src/main/res/drawable/round_button.xml:5]: use dimen value

File: app/src/main/res/layout/fragment_login.xml [hunk 9]
```diff
@@ -15,68 +15,76 @@
...
-                android:layout_width="350dp"
-                android:layout_height="260dp"
-                android:layout_marginStart="@dimen/margin_8"
-                android:layout_marginTop="@dimen/margin_32"
-                android:layout_marginEnd="@dimen/margin_8"
-                android:background="@drawable/ic_illustration_login"
+            <androidx.appcompat.widget.AppCompatTextView
+                android:id="@+id/tvMsg"
+                android:layout_width="wrap_content"
+                android:layout_height="wrap_content"
```
Comment (vikas-infusion) [inline app/src/main/res/layout/fragment_login.xml]: Use common style for duplicate attributes that use in other controls.

File: app/src/main/res/layout/fragment_login.xml [hunk 10]
```diff
@@ -15,68 +15,76 @@
...
+                app:layout_constraintTop_toBottomOf="@+id/tvLogin" />
 
             <com.google.android.material.textfield.TextInputLayout
                 android:id="@+id/field_email"
                 style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                 android:layout_width="0dp"
                 android:layout_height="wrap_content"
-                android:layout_margin="@dimen/margin_20"
+                android:layout_marginTop="@dimen/margin_32"
+                app:boxCornerRadiusBottomEnd="@dimen/margin_10"
```
Comment (vikas-infusion) [inline app/src/main/res/layout/fragment_login.xml]: use common style for this because same thing use in other control also

File: app/src/main/res/layout/fragment_login.xml [hunk 11]
```diff
@@ -116,54 +127,79 @@
...
-                android:textSize="14sp"
+                android:layout_marginTop="@dimen/margin_10"
+                android:text="@string/forgot_password"
+                android:textColor="@color/grey"
+                app:layout_constraintEnd_toEndOf="parent"
+                app:layout_constraintTop_toBottomOf="@+id/field_password" />
+
+            <androidx.appcompat.widget.AppCompatButton
+                android:id="@+id/btnLogin"
+                android:layout_width="match_parent"
```
Comment (vikas-infusion) [inline app/src/main/res/layout/fragment_login.xml]: layout_width define "0dp" and layout_constraintStart_toStartOf="parent"  app:layout_constraintEnd_toEndOf="parent"

**Review by vikas-infusion — DISMISSED** [review]

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt (hunk 4 above)
Comment (vikas-infusion) [reply app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt:57]: done

**Review by vikas-infusion — DISMISSED** [review]

**Review by vikas-infusion — DISMISSED** [review]

**Review by vikas-infusion — APPROVED** [review]
