### PR TITLE
Harsh/doctor time slot disable

### LINKED ISSUE #147: Feature - [User] Doctor time slot not disable.
**Describe the bug**
- If any user book doctor time slot then another user for same doctor that time show time disable
- Until that time slot not reject 
- Pending and approve case another user that time slot show disable not able to book same time slot.
- Call api on date click 
- Mange logic of adapter to show time enable and disable.

**To Reproduce**
1. One user login
2. Select doctor 
3. Book appointment
4. Second user same doctor select and show that time enable that first user already booked.

**Expected behavior**
- If same doctor time slot book any user then another user not able to book, that time slot disable.

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### PR DESCRIPTION
**Pull request by HarshPanchalInfusion**
Time Disable with appointment Table list

### CODE REVIEW

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt [hunk 1]
```diff
@@ -45,27 +43,53 @@ class AppointmentRepository @Inject constructor() {
...
-            val response = fireStore.collection(TABLE_USER_DATA)
-                .whereEqualTo(FIELD_USER_ID, userId)
+            val nextDate = Calendar.getInstance()
+            nextDate.time = date
+            nextDate.add(Calendar.DATE, 1)
+//            Log.d("TAG", "getDoctorById: $date        -->     ${nextDate.time}")
+            val appointmentList = ArrayList<AppointmentModel>()
+            val appointmentResponse = fireStore.collection(TABLE_APPOINTMENT)
+                .whereEqualTo(FIELD_DOCTOR_ID, userId)
+//                .whereEqualTo(FIELD_SELECTED_DATE, date)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt]: Remove commented if not used.

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt [hunk 2]
```diff
@@ -153,7 +176,7 @@ class AppointmentRepository @Inject constructor() {
             nextDate.add(Calendar.DATE, 1)
             val response = firestore.collection(TABLE_APPOINTMENT)
                 .whereEqualTo(FIELD_DOCTOR_ID, userId)
-                .whereEqualTo(FIELD_APPROVED_KEY, ConstantKey.FIELD_PENDING)
+                .whereEqualTo(FIELD_APPROVED_KEY, FIELD_PENDING)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt:123]: Here need only pending Please check once again?

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt [hunk 3]
```diff
@@ -336,5 +359,61 @@ class AppointmentRepository @Inject constructor() {
...
+        doctorDocumentId: String,
+        fireStore: FirebaseFirestore
+    ): ApiResponse<UserDataResponseModel> {
+        return try {
+            val doctorResponse = fireStore.collection(TABLE_USER_DATA)
+                .document(doctorDocumentId)
+                .get()
+                .await()
+            val doctorDataModel1 = doctorResponse.toObject(UserDataResponseModel::class.java)
+            /*doctorDataModel1?.availableTime?.forEachIndexed { timeIndex, addShiftResponseModel ->
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt]: Remove commented code

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt [hunk 4]
```diff
@@ -99,31 +100,35 @@ class AppointmentViewModel @Inject constructor(
...
 
     var updateClick = MutableLiveData(false)
 
 
     private fun get15DaysList() {
-        val currentDate: String = getCurrentDate()
         val dateList = mutableListOf<Date>()
         val calendar = Calendar.getInstance()
-        calendar.time = dateFormatFull.parse(currentDate) as Date
+        calendar.time = dateFormatFull.parse(currentDate1) as Date
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Please give meaning full name, So that in future other developer can understand that used.

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt [hunk 5]
```diff
@@ -206,17 +211,26 @@ class AppointmentViewModel @Inject constructor(
...
     fun getDoctorData() {
-        viewModelScope.launch {
+        /*viewModelScope.launch {
             if (context.isNetworkAvailable()) {
                 setShowProgress(true)
+//                Log.d("TAG", "getDoctorData: $currentDate1")
+
                 when (val response =
-                    appointmentRepository.getDoctorById(doctorId.value.toString(), fireStore)) {
+                    appointmentRepository.getDoctorById(
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Remove commented code

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt [hunk 6]
```diff
@@ -605,5 +635,144 @@ class AppointmentViewModel @Inject constructor(
...
+                    appointmentRepository.getDoctorAppointmentByDate(
+                        doctorId.value.toString(),
+                        selectedDate,
+                        fireStore
+                    )) {
+                    is ApiSuccessResponse -> {
+                        if (timeList.isEmpty()) {
+                            getDoctorData1(response.body)
+                        } else {
+//                            _timeSlotList.value!!.forEachIndexed { index, addShiftTimeModel ->
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Remove commented code

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt [hunk 7]
```diff
@@ -605,5 +635,144 @@ class AppointmentViewModel @Inject constructor(
...
+                                    if (dateFormatter(
+                                            appointmentModel.bookingDateTime,
+                                            FORMATTED_TIME
+                                        ) == dateFormatter(
+                                            addShiftTimeModel.startTime,
+                                            FORMATTED_TIME
+                                        )
+                                    ) {
+                                        timeList.get(timeIndex).isTimeSlotBook = true
+//                                         Log.e("TAG", "getAppointmentData: if", )
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Check all files and remove logs

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt [hunk 8]
```diff
@@ -49,10 +49,10 @@ class LoginViewModel @Inject constructor(
 
     var googleSignInClient: GoogleSignInClient
 
-    val email: MutableLiveData<String> = MutableLiveData()
+    val email: MutableLiveData<String> = MutableLiveData("user1@mailinator.com")
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt]: Please not commit this code

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt (hunk 1 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt]: Done

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt (hunk 3 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt]: Done

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt (hunk 4 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Done

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt (hunk 5 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Done

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt (hunk 6 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Done

File: app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt (hunk 7 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/appointment/AppointmentViewModel.kt]: Done

File: app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt (hunk 8 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/ui/authentication/login/LoginViewModel.kt]: Done

File: app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt (hunk 2 above)
Comment (HarshPanchalInfusion) [reply app/src/main/java/com/android/doctorapp/repository/AppointmentRepository.kt:123]: Done

**Review by vikas-infusion — APPROVED** [review]
