### PR TITLE
completed [User] Profile bottom tab task. Displayed all details of us…

### LINKED ISSUE #82: Bug - [Doctor] Profile Bottom tab
**Describe the bug**
- Show all the details at profile tab.
- Show edit icon on actionbar at right side.
- click on edit icon doctor update their data. only Email and phone number if already verified then not able to do that.

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### LINKED ISSUE #83: Bug - [User] Profile Bottom tab
**Describe the bug**

- show all detials in profile tab.
- show edit icon on action bar right side.
- Click on it user update their data. Only email and phone if verified then not able to do it.

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### LINKED ISSUE #90: Bug - [Doctor] Appointment tab
**Describe the bug**

- Show all appointments with **Approve and Reject**
- Also show appointment status on UI. 
- Approve for gray
- Reject show yellow

### Check List

- [x] I have linked my PR with this task
- [x] I have added comment after completing this task
- [x] I have followed all [guidelines](https://github.com/jaykishan-sewak/doctor-appoint-app/tree/main) for code

### PR DESCRIPTION
**Pull request by namratacn**
…er in profile tab. Displayed edit icon right side in action bar. Clicked on it user can update their data. And if email and contact is verified then user not able to edit those fields.

### CODE REVIEW

File: app/src/main/java/com/android/doctorapp/ui/doctor/AddDoctorViewModel.kt [hunk 1]
```diff
@@ -175,6 +180,7 @@ class AddDoctorViewModel @Inject constructor(
                             degreeLiveList.value = response.body.degree?.toList()
                             specializationLiveList.value = response.body.specialities?.toList()
                             data.value = listOf(userObj)
+                            _getDataResponse.value = response.body!!
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/doctor/AddDoctorViewModel.kt]: Please change variable name it is not function.

File: app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/AppointmentDoctorFragment.kt [hunk 2]
```diff
@@ -60,7 +60,10 @@ class AppointmentDoctorFragment :
         layoutBinding.recyclerView.adapter = adapter
 
         viewModel.finalAppointmentList.observe(viewLifecycleOwner) {
-            adapter.filterList(it)
+            if (it != null && it.isNotEmpty()) {
+                adapter.filterList(it)
+                viewModel.dataFound.postValue(true)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/AppointmentDoctorFragment.kt]: use like below
viewModel.dataFound.value = true

File: app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/RequestDoctorFragment.kt [hunk 3]
```diff
@@ -78,7 +78,10 @@ class RequestDoctorFragment :
             viewModel.isRequestCalender.value = false
         }
         viewModel.requestAppointmentList.observe(viewLifecycleOwner) {
-            adapter.filterList(it)
+            if (it != null && it.isNotEmpty()) {
+                adapter.filterList(it)
+                viewModel.dataFound.postValue(true)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/RequestDoctorFragment.kt]: use like below
viewModel.dataFound.value = true

File: app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/SelectedDateAppointmentsFragment.kt [hunk 4]
```diff
@@ -76,7 +76,10 @@ class SelectedDateAppointmentsFragment :
             viewModel.isCalender.value = false
         }
         viewModel.appointmentList.observe(viewLifecycleOwner) {
-            adapter.filterList(it)
+            if (it != null && it.isNotEmpty()) {
+                adapter.filterList(it)
+                viewModel.dataFound.postValue(true)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/doctordashboard/doctorfragment/SelectedDateAppointmentsFragment.kt]: use like below
viewModel.dataFound.value = true

File: app/src/main/java/com/android/doctorapp/ui/profile/ProfileFragment.kt [hunk 5]
```diff
@@ -63,6 +84,31 @@ class ProfileFragment : BaseFragment<FragmentProfileBinding>(R.layout.fragment_p
...
+        }
+        viewModel.phoneClick.observe(viewLifecycleOwner) {
+            if (it != null && it.isNotEmpty()) {
+                val intent = Intent(Intent.ACTION_DIAL)
+                intent.data = Uri.parse("tel: $it")
+                requireActivity().startActivity(intent)
+            }
+        }
+        viewModel.emailClick.observe(viewLifecycleOwner) {
+            if (it != null && it.isNotEmpty()) {
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/profile/ProfileFragment.kt]: make common method for email send

File: app/src/main/java/com/android/doctorapp/ui/profile/ProfileFragment.kt [hunk 6]
```diff
@@ -63,6 +84,31 @@ class ProfileFragment : BaseFragment<FragmentProfileBinding>(R.layout.fragment_p
...
+
+        viewModel.getUserProfileData()
+        viewModel.isEdit.observe(viewLifecycleOwner) {
+            if (it) {
+                findNavController().navigate(
+                    R.id.action_user_profile_to_updateUserProfile
+                )
+            }
+        }
+        viewModel.phoneClick.observe(viewLifecycleOwner) {
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/profile/ProfileFragment.kt:96]: make common method for phone number. phone number as parameter of function. That is help full to other screen if needed.

File: app/src/main/java/com/android/doctorapp/ui/profile/ProfileViewModel.kt [hunk 7]
```diff
@@ -51,6 +73,45 @@ class ProfileViewModel @Inject constructor(
...
+        viewModelScope.launch {
+            var recordId: String = ""
+            session.getString(USER_ID).collectLatest {
+                recordId = it.orEmpty()
+                if (context.isNetworkAvailable()) {
+                    setShowProgress(true)
+                    when (val response =
+                        profileRepository.getProfileRecordById(recordId, fireStore)) {
+                        is ApiSuccessResponse -> {
+                            userProfileDataResponse.value = response.body!!
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/ui/profile/ProfileViewModel.kt:84]: use this    userProfileDataResponse object to show age. i think no need to extra age variable.

File: app/src/main/java/com/android/doctorapp/util/extension/ContextExtension.kt [hunk 8]
```diff
@@ -204,3 +204,24 @@ fun convertToFormatDate(
         ""
     }
 }
+
+fun calculateAge(dateOfBirth: String): String {
+    return try {
+        val dateFormatter = SimpleDateFormat(FULL_DATE_FORMAT)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/util/extension/ContextExtension.kt]: val dateFormatter = SimpleDateFormat(FULL_DATE_FORMAT,Locale.getDefault())

File: app/src/main/java/com/android/doctorapp/util/extension/ContextExtension.kt [hunk 9]
```diff
@@ -204,3 +204,24 @@ fun convertToFormatDate(
...
+        val dob: Date = dateFormatter.parse(dateOfBirth)
```
Comment (vikas-infusion) [inline app/src/main/java/com/android/doctorapp/util/extension/ContextExtension.kt]: Also check warring of lines and fixed according it.

**Review by vikas-infusion — APPROVED** [review]
